[feat/viewCount] 조회수 증가 로직 구현
class071/timotae pull request #65
Opened 2022-04-20 07:32 UTC by we4sley

synchronized 키워드로 메소드 동시 접근 제어
volatile 키워드로 필드의 최신 값을 동기화

2022-04-20 13:11 UTC, gnoesnooj requested changes

2022-04-20 13:11 UTC, gnoesnooj commented on src/main/java/com/daily/timotae/domain/Post.java
> +    private volatile int viewCount;
조회수는 db에서 관리 안해주는거 ?

2022-04-20 13:11 UTC, gnoesnooj commented on src/test/java/com/daily/timotae/service/BoardServiceTest.java
> +@SpringBootTest
테스트하고나서 @SpringBootTest 어노테이션 주석처리 해주세요 배포 과정에서 오류나요 ㅠ

2022-04-20 13:11 UTC, gnoesnooj approved these changes

2022-04-24 08:33 UTC, we4sley commented on src/main/java/com/daily/timotae/domain/Post.java
> +    private volatile int viewCount;
컬럼 설정 했습니다.

2022-04-24 08:33 UTC, we4sley commented on src/test/java/com/daily/timotae/service/BoardServiceTest.java
> +@SpringBootTest
주석처리 했습니다.

2022-04-24 08:34 UTC, merged